yameenyousuf1211/Story-Time-backend

models/notificationModel.js
package-lock.json
package.json
utils/firebase.json
utils/index.js

fcm work implemented as per new firebase strategy (only required firebase.json file from frontend)

fcm work implemented

---

controllers/userController.js

Refactor: Admin Panel

---

socket/index.js

Close Chat Bug

---

controllers/authController.js
middlewares/auth.js

Added account deactivation check in login API

Account Deactivation handling in login & social login APIs

---

controllers/queries/userQueries.js

Refactor getFriendsQuery 

---

socket/index.js

…onse & and include chat object similar to get-chat-list object

minor issue fixed

---

server.js

- Grand Parent
- Parent
- Child
You …

add localhost to cors

---

server.js

- Grand Parent
- Parent
- Child
You …

Dev to Main

---

controllers/userController.js
models/supportMessageModel.js
models/userModel.js
package-lock.json
package.json
socket/index.js
utils/index.js

… and user
This PR is related to [86eq2n2xd](https://app.clickup.com/t/86eq2n2xd)
modified sockets events of  "sending message" and "get chat messages" to get unread-count of messages on real-time 
- Visit [[url-to-login-page](https://modventure.postman.co/workspace/ad586ed0-d507-4fb7-a174-26f2ed60a2a5)](#)
- listen on send-message event
- listen on getChatMessages event
- send a message though user and listen for admin in another postman window
- Grand Parent
- Parent
- Child
- Include links, images, …

Refactor socket event

---

utils/index.js
utils/s3Upload.js

- Adjusted ContentType and ContentEncoding logic to ensure proper handling of PDFs and base64 images.
- Ensured that files retain their original MIME type during upload.
- Fixed issues with PDF files not opening properly after upload to S3.
- [*] story-time-backend
This PR is related to [Click-up Ticket Number](https://app.clickup.com/t/86eq2mk9z)
- Adjusted ContentType and ContentEncoding logic to ensure proper handling of PDFs and base64 images.
- Ensured that files retain their original MIME type during upload.
- Fixed issues with PDF files not opening properly after upload to S3.
Verify Image Uploads
Visit [Upload Page](https://github.com/yameenyousuf1211/Story-Time-backend/compare/pvt-ali-attachment-fixed?expand=1#) …

fix(upload): correct S3 upload handling for PDFs and base64 images

---

api/rootApi.js
controllers/rootController.js
utils/index.js
utils/s3Upload.js

- [*] story-time-backend
This PR is related to [Click-up Ticket Number](https://app.clickup.com/t/86eq2z557)
Pull Request Summary
Title: Fix Image Download and API Integration
Description:
This pull request addresses issues with downloading images and integrating the image download API. It includes the following updates:
Updated the downloadImage API endpoint to stream image data directly to the client rather than encoding it in base64. This change ensures correct file handling and download behavior.
Added response headers to specify the content type and suggest a filename for the downloaded file.

Pvt ali download image api

---

api/userApi.js
controllers/authController.js
controllers/userController.js
models/guestModel.js
models/userModel.js
validations/userValidation.js

This PR is related to [86eq21zt8](https://app.clickup.com/t/86eq21zt8)
This PR is related to [86eq30ee6](https://app.clickup.com/t/86eq30ee6)
This PR is related to [86eq23b20](https://app.clickup.com/t/86eq23b20)
This PR is related to [86eq3kzty](https://app.clickup.com/t/86eq3kzty)
**86eq21zt8** => when user login from manual login procedure after registering through social registration flow, this error was thrown "data and hash argument ", handled the issue to show a meaningful error 
**86eq30ee6** => remove authorization from user/subscribe api as user can subscribe without logging in the app
**86eq23b20** => removed email required validation when updating user profile as users registering through apple can hide their email
**86eq3kzty** => binded fcmToken to guestID so when the same …

Hash argument

---

api/rootApi.js
api/userApi.js
controllers/authController.js
controllers/rootController.js
controllers/userController.js
models/guestModel.js
models/userModel.js
utils/s3Upload.js
validations/userValidation.js

- Grand Parent
- Parent
- Child
You …

dev to main PR (Bug fixes)

---

api/rootApi.js
api/storyApi.js
controllers/queries/storyQueries.js
controllers/rootController.js
controllers/storyController.js
controllers/userController.js

- Grand Parent
- Parent
- Child
You …

dev to main PR

---

controllers/notificationController.js
models/notificationModel.js
utils/index.js

…ication data in Firebase message
This PR is related to [86eq3x1mz](https://app.clickup.com/t/86eq3x1mz)
Populated the data field that is being sent with the notification
- Grand Parent
- Parent
- Child
You can also use these general Markdown guides for the …

notification bug

---

controllers/authController.js
controllers/queries/userQueries.js
controllers/userController.js
models/followingModel.js

This PR is related to [86eq5p37j](https://app.clickup.com/t/86eq5p37j)
optimized sendVerficationCode API
Implemented indexing on following model which reduced the response time of fetch users and stories API's from 2 seconds to 500ms (approx.)
- Grand Parent
- Parent
- Child
> Note: You can add qoutes as well by typing the > key and a …

Code optimization

---

controllers/authController.js
controllers/notificationController.js
controllers/queries/userQueries.js
controllers/userController.js
models/followingModel.js
models/notificationModel.js
socket/index.js
utils/index.js

- Grand Parent
- Parent
- Child
You …

dev into prod

---

api/categoryApi.js
api/storyApi.js
controllers/categoryController.js
controllers/queries/categoryQueries.js
controllers/queries/storyQueries.js
controllers/storyController.js
models/categoryModel.js
models/storyModel.js
models/userModel.js
package-lock.json
package.json
utils/index.js
utils/s3Upload.js
validations/storyValidation.js

This PR is related to [86eqa004c](https://app.clickup.com/t/86eqa004c)
This PR is related to [86eq9qzw1](https://app.clickup.com/t/86eq9qzw1)
=> Notification were not working, converted data to string before sending the notification which resolved the issue
=> updated s3Uplaoding function to handle video uploading
=> updated story model and validation to handle video stories 
- Grand Parent
- Parent
- Child
2. lorem …

Modifications in video story and video uploading

---

validations/storyValidation.js

- Grand Parent
- Parent
- Child
You …

Refactor: Make thumbnail field optional for video stories

---

api/storyApi.js
controllers/categoryController.js
controllers/queries/categoryQueries.js
controllers/queries/storyQueries.js
controllers/storyController.js

- Grand Parent
- Parent
- Child
You …

CR Admin Panel 

---

controllers/queries/storyQueries.js
controllers/storyController.js

- Grand Parent
- Parent
- Child
You …

Addded search functionality to fetchStoriesByLikesQuery

---

.github/workflows/main.yml
api/categoryApi.js
api/storyApi.js
controllers/categoryController.js
controllers/queries/categoryQueries.js
controllers/queries/storyQueries.js
controllers/queries/userQueries.js
controllers/storyController.js
models/categoryModel.js
models/storyModel.js
models/userModel.js
package-lock.json
package.json
server.js
utils/index.js
utils/s3Upload.js
validations/storyValidation.js

- Grand Parent
- Parent
- Child
You …

DEV to PROD

---

controllers/notificationController.js

…receiver
This PR is related to [86eqdcx3v](https://app.clickup.com/t/86eqdcx3v)
- Grand Parent
- Parent
- Child
You can also …

Refactor: Update notificationController

---

package-lock.json
package.json
utils/mailer.js

- Grand Parent
- Parent
- Child
You …

OTP send using mailtrap service

---

package-lock.json
package.json
utils/mailer.js

- Grand Parent
- Parent
- Child
You …

otp config using mailtrap

---

.gitignore
api/userApi.js
controllers/userController.js
package-lock.json
package.json
utils/index.js

This PR is related to [86eqdxr0g](https://app.clickup.com/t/86eqdxr0g)
Added API to fetch the total download of App
need to add GA_PROPERTY_ID in .env
and also add serviceAccountKey.json file
- Grand Parent
- Parent
- Child
> Note: You can add qoutes as well by …

API to fetch total downloads of App

---

api/userApi.js
controllers/userController.js
models/userModel.js
validations/userValidation.js

- Grand Parent
- Parent
- Child
You …

updated user schema to handle user subscriptions

---

api/userApi.js
controllers/userController.js
models/userModel.js
validations/userValidation.js

- Grand Parent
- Parent
- Child
You …

main <= dev

---

controllers/userController.js

- Grand Parent
- Parent
- Child
You …

fix: isActive Key always true issue fixed

---

models/userModel.js

- Grand Parent
- Parent
- Child
You …

refactor: Update getPremiumNonPremiumCount function

---

models/notificationModel.js

added a check to send storyId in data if type of notification is not admin, else send the storyID
- Grand Parent
- Parent
- Child
You can also use these general Markdown guides for …

refactor: Only include storyId if it's not an admin notification
